name = "backend_cloudflare_worker"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="your db url connectionpool"
JWT_SECRET="your secret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
